name: Deploy to dev
on: [workflow_dispatch, pull_request, push]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install
      - name: Push to Workers
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          SECRETS: |
            VERSION
            BRANCH
        env:
          VERSION: ${{ github.sha }}
          BRANCH: ${{ github.ref }}